### ISSUE TITLE
Co-authors connections

### ISSUE THREAD

**Issue by valeriocos** [SOM-Research/metaScience#23]
Currently, in the graph all the edges have the same size, thus it's not possible to understand the connection strength between two authors.
The thickness of the edge between two authors should depend on the number of papers published together, what do you think?

**Comment by jlcanovas** [comment]
I guess you are referring to the co-author visualization for venues (there are no edges in the visualization for co-author for authors), In this case thickness edges do vary (check for instance the "icmt" conference). Maybe you detected a special case?

**Comment by valeriocos** [comment]
yes, I was referring to the co-author visualization for venues. I was looking at ECMFA, in particular I was checking authors that have between 5 and 6 papers together. Now looking carefully I can see that there is a (tiny) difference in the edges' thickness. Maybe we could think to add a label to the edge or increase the thickness

**Comment by jlcanovas** [comment]
Maybe we can play a bit with the edges' thickness to see if we can improve the situation. The thing is that when the graph contains a lot of nodes (as usually happens) it's difficult even to read authors' names (which forces the user to zoom in and therefore can also help to see the different edges' thicknesses).

**Comment by jlcanovas** [comment]
I've been playnig a bit with edges' thicknesses and I've checked that thicker style are less readable so I've increased the thickness only a bit.

To compensate, I've added a tooltip window that appears when the user pass the mouse over the edges and shows the value for the collaboration.
