### ISSUE TITLE
Imprecise values in openness information panel 

### ISSUE THREAD

**Issue by valeriocos** [SOM-Research/metaScience#26]
I found some inconsistencies in the openness information panel when testing the conference ICMT. Below the result from the test and metascience

| - | test | metascience |
| --- | --- | --- |
| year | from_community/from_new_comers | from_community/from_new_comers |
| "2008" | [0.0,              100.0] | [0.0,              100.0], |
| "2009" | [10.53,          63.16] | [11.0,              63.0], |
| "2010" | [11.11,          44.44] | [11.0,              44.0], |
| "2011" | [13.33,          60.0 ] | [13.0,              60.0], |
| "2012" | [31.58,          31.58] | [32.0,              32.0], |
| "2013" | [33.33,           22.22] | [33.0,              22.0], |
| "2014" | [7.14,             21.43] | [7.0,              21.0] |

**Comment by jlcanovas** [comment]
The problem was in the number of decimals configured in the server.
