### ISSUE TITLE
Imprecise value for "average perishing rate"

### ISSUE THREAD

**Issue by valeriocos** [SOM-Research/metaScience#27]
The average perishing rate reported by the test for ICMT is 76.42, while in metascience is 76.68.
However metascience and the testing script generate the same values for the Turnover information panel

**Comment by jlcanovas** [comment]
I guess the issue is referring to result values for _icmt_ conference, as reported in #26?

**Comment by jlcanovas** [comment]
The problem was the average calculation (Java-based vs. SQL-based). We now use the SQL-based version.
