### ISSUE TITLE
Imprecise value for "average openness rate"

### ISSUE THREAD

**Issue by valeriocos** [SOM-Research/metaScience#28]
the result generated by the test for ICMT are not consistent with the ones in metascience

| source | from_community | from_new_comers |
| --- | --- | --- |
| test | 15.29 | 48.98 |
| metascience | 66.59 | 48.98 |

**Comment by jlcanovas** [comment]
I guess the issue is referring to result values for _icmt_ conference, as reported in #26?

**Comment by valeriocos** [comment]
yes, I update the issue

**Comment by jlcanovas** [comment]
The problem was in initVenue.js, which was getting a wrong field from the JSON
