### ISSUE TITLE
Venue author collaborations graph should show selected author collaborations 

### ISSUE THREAD

**Issue by rBoncorps** [SOM-Research/metaScience#29]
When an author is selected, the graph should zoom in and scale to content to show the collaborations for the selected author efficiently.
A problem appears if the graph is already zoom in and a author is selected. This may result in the selected collaborations being out of the display. The user has then to zoom out to find the selected collaborations and zoom back in to be able to read.

**Comment by rBoncorps** [comment]
This will be adressed in v0.3.0

**Comment by jlcanovas** [comment]
Fixed and merged into 0.2.1 in #33
